First-Join-Spawn: ''
Spawn-No-Respawn: true
Force-Spawn-On-Death: false
Force-Spawn-On-Join: false
Lang:
  Prefix: '&#696969[&#9632faN&#9831efe&#9a30e4o&#9b2ed9S&#9d2dcep&#9f2cc3a&#a12bb8w&#a229adn&#a428a2P&#a62797o&#a8268ci&#a92481n&#ab2376t&#ad226bs&#696969]&f '
  Invalid-Spawn-Point: "&c'&4{input}&c' is not a valid spawn! Try using one from tab complete."
  Invalid-Player: "&c'&4{input}&c' is not a valid player. Make sure they're online!"
  Invalid-Permission-Spawn-All: "&cYou don't have permission to teleport everyone to spawn!"
  Spawn-Already-Exists: "&cSpawn '&4{input}&c' already exists! Try using another name!"
  Spawn-Created: "&aCreated Spawn {spawn} at {x}, {y}, {z} in world {world} with a priority of {priority}!"
  Spawn-Deleted: "&cSuccessfully deleted spawn: &4{spawn}&c."
  No-Spawn-Message: '&cYou have no active spawn point!'
  Teleported-Message: '&aTeleported to x:{x} y:{y} z:{z} in world {world}!'
  No-Spawn-Message-Admin: '&c{player} has no specific spawn point!'
  Force-Spawn-Message-Admin: '&aYou sent {player} to their spawn!'
  Force-Specific-Spawn-Admin: '&aYou sent {player} to the spawn point: {spawn}'
  Force-Spawn-Message-Player: '&aYou have been sent to spawn!'
  Force-Specific-Spawn-Player: '&aYou have been sent to {spawn}!'
  Teleported-All-Spawn-Admin: "&aSuccessfully teleported {succeeded}/{amount} players to their spawn."
  Teleported-All-Specific-Spawn-Admin: "&aSuccessfully teleported {amount} players to spawn point: {spawn}."


